import { useState, useEffect, useRef } from "react";
import { Html5Qrcode } from "html5-qrcode";
import { api } from "@/lib/axios";
import { RefreshCw, CheckCircle2, XCircle, Camera } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

export default function SecurityGuardPickupScannerPage() {
  const [result, setResult] = useState<any>(null);
  const [error, setError] = useState<string>('');
  const [scanning, setScanning] = useState(true);
  const scannerRef = useRef<Html5Qrcode | null>(null);
  const hasScannedRef = useRef(false);

  useEffect(() => {
    let html5QrCode: Html5Qrcode;

    const startScanner = async () => {
      if (scanning) {
        hasScannedRef.current = false;
        try {
          html5QrCode = new Html5Qrcode("qs-reader");
          scannerRef.current = html5QrCode;

          await html5QrCode.start(
            { facingMode: "environment" },
            { fps: 10, qrbox: { width: 250, height: 250 }, aspectRatio: 1.0 },
            (decodedText) => handleScanSuccess(decodedText),
            () => {}
          );
        } catch (err) {
          console.error("Camera error", err);
          setError("Camera logic failed. Requires HTTPS for permissions on mobile.");
          setScanning(false);
        }
      }
    };

    startScanner();

    return () => {
      if (html5QrCode && html5QrCode.isScanning) {
        html5QrCode.stop().then(() => html5QrCode.clear()).catch(console.error);
      }
    };
  }, [scanning]);

  const handleScanSuccess = async (decodedText: string) => {
    if (hasScannedRef.current) return;
    hasScannedRef.current = true;
    
    if (scannerRef.current) {
      try {
        await scannerRef.current.stop();
        scannerRef.current.clear();
      } catch (err) {}
    }
    setScanning(false);
    
    try {
      const data = JSON.parse(decodedText);
      verifyToken(data.token);
    } catch (e) {
      setError("Invalid QR Code structure. This is not a Pickup QR.");
    }
  };

  const verifyToken = async (token: string) => {
    try {
      const res = await api.post("/adm/pickups/verify", { qrToken: token });
      setResult(res.data);
      setError('');
    } catch (err: any) {
      setError(err.response?.data?.message || 'Verification failed on server side.');
      setResult(null);
    }
  };

  const resetScan = () => {
    setResult(null);
    setError('');
    setScanning(true);
  };

  return (
    <div className="max-w-2xl mx-auto space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight text-foreground">Pickup QR Scanner</h1>
        <p className="text-muted-foreground mt-2">
          Scan a student pickup QR code generated by an authorized guardian.
        </p>
      </div>

      <Card className="overflow-hidden border-border bg-card">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Camera className="h-5 w-5" /> Live Camera Feed
          </CardTitle>
          <CardDescription>Hover the scanner over the parent's device screen.</CardDescription>
        </CardHeader>
        <CardContent className="p-0 sm:p-6">
          {scanning ? (
            <div className="relative">
              <div id="qs-reader" className="w-full bg-black min-h-[300px] overflow-hidden rounded-xl border-4 border-dashed border-emerald-500/50"></div>
              <div className="absolute inset-0 pointer-events-none flex items-center justify-center">
                 <p className="text-emerald-400 font-mono animate-pulse bg-black/50 px-4 py-2 rounded-full backdrop-blur-md">Scanning for tokens...</p>
              </div>
            </div>
          ) : (
            <div className="p-8 text-center space-y-6">
              <Button onClick={resetScan} size="lg" className="rounded-full shadow-lg h-14 px-8 text-lg font-semibold">
                <RefreshCw className="mr-2 h-5 w-5" /> Scan Another QR
              </Button>
            </div>
          )}

          {/* Result Block */}
          {!scanning && (result || error) && (
            <div className="p-6 m-4 sm:m-0 sm:mt-6 rounded-2xl border-2 shadow-xl animate-in fade-in slide-in-from-bottom-4 data-[state=error]:border-rose-500 data-[state=error]:bg-rose-500/10 data-[state=success]:border-emerald-500 data-[state=success]:bg-emerald-500/10" data-state={error ? "error" : "success"}>
              {error ? (
                <div className="text-center space-y-3">
                  <XCircle className="mx-auto h-16 w-16 text-rose-500" />
                  <h3 className="text-2xl font-bold text-rose-600 dark:text-rose-400">Scan Rejected</h3>
                  <p className="font-medium text-foreground">{error}</p>
                </div>
              ) : (
                <div className="text-center space-y-4">
                  <CheckCircle2 className="mx-auto h-20 w-20 text-emerald-500" />
                  <h3 className="text-3xl font-black text-emerald-600 dark:text-emerald-400">AUTHORIZED</h3>
                  
                  <div className="bg-card border shadow-inner p-6 rounded-xl text-left space-y-3 mx-auto max-w-sm mt-4 relative overflow-hidden">
                    <div className="absolute top-0 right-0 bg-emerald-500 text-white text-xs font-bold px-3 py-1 rounded-bl-lg">LIVE VERIFIED</div>
                    <p className="text-lg"><span className="text-muted-foreground mr-2">Child:</span> <span className="font-bold">{result.studentName}</span></p>
                    <p className="text-lg"><span className="text-muted-foreground mr-2">Class:</span> <span className="font-semibold">{result.studentClassInfo}</span></p>
                    <p className="text-lg"><span className="text-muted-foreground mr-2">Parent/Guardian:</span> <span>{result.generatedByName}</span></p>
                  </div>
                </div>
              )}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
