import { useState, useEffect } from "react";
import { api } from "@/lib/axios";
import { format } from "date-fns";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";

export default function AdminPickupLogsPage() {
  const [pickups, setPickups] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    fetchLogs();
  }, []);

  const fetchLogs = async () => {
    setLoading(true);
    try {
      const res = await api.get("/adm/pickups");
      setPickups(res.data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'VERIFIED':
        return <Badge variant="default" className="bg-emerald-500 hover:bg-emerald-600">VERIFIED</Badge>;
      case 'EXPIRED':
        return <Badge variant="destructive" className="bg-rose-500 hover:bg-rose-600">EXPIRED</Badge>;
      case 'FAILED':
        return <Badge variant="destructive" className="bg-red-500 hover:bg-red-600">FAILED</Badge>;
      default:
        return <Badge variant="outline" className="border-amber-500 text-amber-500">PENDING</Badge>;
    }
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight text-foreground">QR Pickup Logs</h1>
        <p className="text-muted-foreground mt-2">
          Monitor all generated student pickup QR codes and their verification status.
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Pickup History</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="rounded-md border">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Generated At</TableHead>
                  <TableHead>Student</TableHead>
                  <TableHead>Class</TableHead>
                  <TableHead>Generated By</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Verified At</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {loading ? (
                  <TableRow>
                    <TableCell colSpan={6} className="h-24 text-center">Loading logs...</TableCell>
                  </TableRow>
                ) : pickups.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={6} className="h-24 text-center">No pickup records found.</TableCell>
                  </TableRow>
                ) : (
                  pickups.map((log) => (
                    <TableRow key={log.uuid}>
                      <TableCell className="whitespace-nowrap">
                        {log.generatedAt ? format(new Date(log.generatedAt), "MMM d, yyyy h:mm a") : "-"}
                      </TableCell>
                      <TableCell className="font-medium">{log.studentName}</TableCell>
                      <TableCell>{log.studentClassInfo}</TableCell>
                      <TableCell>{log.generatedByName}</TableCell>
                      <TableCell>{getStatusBadge(log.status)}</TableCell>
                      <TableCell className="whitespace-nowrap">
                        {log.verifiedAt ? format(new Date(log.verifiedAt), "MMM d, yyyy h:mm a") : "-"}
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
